export const GET_VIDEOGAMES = 'GET_VIDEOGAMES'
export const GET_VG_BY_ID = 'GET_VG_BY_ID'
export const ADD_VIDEOGAME = 'ADD_VIDEOGAME'
export const GET_GENRE = 'GET_GENRE'
export const GET_VG_BY_NAME = 'GET_VG_BY_NAME'
export const DELETE_VG = 'DELETE_VG'